FROM python:3.12-slim
WORKDIR /app
COPY requirements.cpu.txt .
RUN pip install --no-cache-dir torch==2.8.0 --index-url https://download.pytorch.org/whl/cpu && pip install --no-cache-dir -r requirements.cpu.txt
COPY main.py .
EXPOSE 8102
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8102"]
