package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

func (s *server) chat(w http.ResponseWriter,r *http.Request){ started:=time.Now(); requestID:=fmt.Sprintf("req-%d",time.Now().UnixNano()); w.Header().Set("X-NDHIS-Request-ID",requestID); var input chatRequest; decoder:=json.NewDecoder(r.Body); decoder.DisallowUnknownFields(); if err:=decoder.Decode(&input); err!=nil { writeJSON(w,http.StatusBadRequest,map[string]string{"error":"invalid chat request"}); s.audit(r,requestID,"/api/chat","",http.StatusBadRequest,started); return }; if err:=validateMessages(input.Messages); err!=nil { writeJSON(w,http.StatusBadRequest,map[string]string{"error":err.Error()}); s.audit(r,requestID,"/api/chat","",http.StatusBadRequest,started); return }; decision,err:=s.route(r.Context(),input.Messages); if err!=nil { writeJSON(w,http.StatusBadGateway,map[string]string{"error":err.Error()}); s.audit(r,requestID,"/api/chat","",http.StatusBadGateway,started); return }; if decision.Type=="answer" { writeJSON(w,http.StatusOK,chatResponse{Answer:decision.Content,LatencyMS:time.Since(started).Milliseconds(),RequestID:requestID}); s.audit(r,requestID,"/api/chat","",http.StatusOK,started); return }; toolResult,err:=s.executeTool(r.Context(),decision.Name,decision.Arguments); if err!=nil { writeJSON(w,http.StatusBadGateway,map[string]string{"error":err.Error()}); s.audit(r,requestID,"/api/chat",decision.Name,http.StatusBadGateway,started); return }; answer,err:=s.finalize(r.Context(),input.Messages,decision,toolResult); if err!=nil { writeJSON(w,http.StatusBadGateway,map[string]string{"error":err.Error()}); s.audit(r,requestID,"/api/chat",decision.Name,http.StatusBadGateway,started); return }; writeJSON(w,http.StatusOK,chatResponse{Answer:answer,Tool:decision.Name,Arguments:decision.Arguments,LatencyMS:time.Since(started).Milliseconds(),RequestID:requestID}); s.audit(r,requestID,"/api/chat",decision.Name,http.StatusOK,started) }
func validateMessages(messages []message) error { if len(messages)==0{return errors.New("at least one message is required")}; if len(messages)>maxChatMessages{return fmt.Errorf("at most %d messages are allowed",maxChatMessages)}; for index,item:=range messages { if item.Role!="user"&&item.Role!="assistant" { return fmt.Errorf("message %d has invalid role",index+1) }; content:=strings.TrimSpace(item.Content); if content=="" { return fmt.Errorf("message %d is empty",index+1) }; if len([]rune(content))>maxMessageCharacters { return fmt.Errorf("message %d exceeds %d characters",index+1,maxMessageCharacters) } }; return nil }
func (s *server) route(ctx context.Context,messages []message)(agentDecision,error){ tools,_:=json.Marshal(toolManifest); system:="You are the NDHIS local AI router. Select at most one tool. Do not invent clinical facts. Return exactly one JSON object and no markdown. For a tool call use {\"type\":\"tool\",\"name\":\"tool_name\",\"arguments\":{...}}. If no tool is needed use {\"type\":\"answer\",\"content\":\"answer\"}. Available tools: "+string(tools); requestMessages:=append([]message{{Role:"system",Content:system}},messages...); content,err:=s.callAgent(ctx,requestMessages,220); if err!=nil{return agentDecision{},err}; decision,err:=parseAgentDecision(content); if err!=nil{return agentDecision{},err}; return validateDecision(decision) }
func parseAgentDecision(content string)(agentDecision,error){ trimmed:=strings.TrimSpace(content); start,end:=strings.Index(trimmed,"{"),strings.LastIndex(trimmed,"}"); if start<0||end<start{return agentDecision{},errors.New("agent returned no JSON object")}; var decision agentDecision; decoder:=json.NewDecoder(strings.NewReader(trimmed[start:end+1])); if err:=decoder.Decode(&decision); err!=nil{return agentDecision{},fmt.Errorf("invalid agent JSON: %w",err)}; return decision,nil }
func validateDecision(decision agentDecision)(agentDecision,error){ switch decision.Type { case "answer": decision.Content=strings.TrimSpace(decision.Content); if decision.Content==""{return agentDecision{},errors.New("agent answer is empty")}; if len([]rune(decision.Content))>4000{return agentDecision{},errors.New("agent answer exceeds output limit")}; decision.Name,decision.Arguments="",nil; return decision,nil; case "tool": if _,ok:=allowedTools[decision.Name];!ok{return agentDecision{},fmt.Errorf("agent selected unsupported tool: %s",decision.Name)}; args,err:=validateToolArguments(decision.Name,decision.Arguments); if err!=nil{return agentDecision{},err}; decision.Arguments,decision.Content=args,""; return decision,nil; default:return agentDecision{},errors.New("agent returned invalid decision type") } }
func (s *server) finalize(ctx context.Context,messages []message,decision agentDecision,result json.RawMessage)(string,error){ requestMessages:=append([]message{},messages...); requestMessages=append(requestMessages,message{Role:"assistant",Content:mustJSON(decision)},message{Role:"user",Content:"Tool result: "+string(result)+". Return exactly {\"type\":\"answer\",\"content\":\"concise grounded answer\"}. Do not add facts not present in the tool result."}); content,err:=s.callAgent(ctx,requestMessages,320); if err!=nil{return "",err}; final,err:=parseAgentDecision(content); if err!=nil{return "",err}; final,err=validateDecision(final); if err!=nil{return "",err}; if final.Type!="answer"{return "",errors.New("agent did not return a final answer")}; return final.Content,nil }
func (s *server) callAgent(ctx context.Context,messages []message,maxTokens int)(string,error){ body,err:=json.Marshal(agentRequest{Model:s.cfg.AgentModel,Messages:messages,Temperature:0,MaxTokens:maxTokens,ResponseFormat:map[string]string{"type":"json_object"}}); if err!=nil{return "",err}; req,err:=http.NewRequestWithContext(ctx,http.MethodPost,s.cfg.AgentURL,bytes.NewReader(body)); if err!=nil{return "",err}; req.Header.Set("Content-Type","application/json"); resp,err:=s.client.Do(req); if err!=nil{return "",err}; defer resp.Body.Close(); if resp.StatusCode!=http.StatusOK{payload,_:=io.ReadAll(io.LimitReader(resp.Body,4096));return "",fmt.Errorf("agent status %d: %s",resp.StatusCode,strings.TrimSpace(string(payload)))}; var output agentResponse; decoder:=json.NewDecoder(io.LimitReader(resp.Body,maxAgentResponse)); if err:=decoder.Decode(&output);err!=nil{return "",fmt.Errorf("invalid agent response: %w",err)}; if len(output.Choices)==0{return "",errors.New("agent returned no choices")}; content:=strings.TrimSpace(output.Choices[0].Message.Content); if content==""{return "",errors.New("agent returned empty content")}; return content,nil }
