package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

func validateToolArguments(name string,args map[string]any)(map[string]any,error){ if args==nil{args=map[string]any{}}; clean:=map[string]any{}; requireString:=func(key string,max int)(string,error){ value,ok:=args[key].(string); value=strings.TrimSpace(value); if !ok||value==""||len([]rune(value))>max{return "",fmt.Errorf("%s requires a valid %s",name,key)};return value,nil }; horizon:=func()(int,error){ value,ok:=numberAsInt(args["horizon_days"]); if !ok||value<1||value>90{return 0,fmt.Errorf("%s requires horizon_days between 1 and 90",name)};return value,nil }; switch name { case "forecast_patient_volume","forecast_bed_occupancy": facility,err:=requireString("facility",80);if err!=nil{return nil,err};department,err:=requireString("department",80);if err!=nil{return nil,err};days,err:=horizon();if err!=nil{return nil,err};clean["facility"],clean["department"],clean["horizon_days"]=facility,department,days; case "forecast_disease_incidence": facility,err:=requireString("facility",80);if err!=nil{return nil,err};disease,err:=requireString("disease",120);if err!=nil{return nil,err};days,err:=horizon();if err!=nil{return nil,err};clean["facility"],clean["disease"],clean["horizon_days"]=facility,disease,days; case "get_radiology_result":resultID,err:=requireString("result_id",160);if err!=nil{return nil,err};clean["result_id"]=resultID; case "get_service_status": default:return nil,fmt.Errorf("unknown tool: %s",name) }; return clean,nil }
func numberAsInt(value any)(int,bool){ switch typed:=value.(type){case float64:integer:=int(typed);return integer,typed==float64(integer);case int:return typed,true;case json.Number:integer,err:=typed.Int64();return int(integer),err==nil;default:return 0,false} }
func (s *server) executeTool(ctx context.Context,name string,args map[string]any)(json.RawMessage,error){ validated,err:=validateToolArguments(name,args);if err!=nil{return nil,err};switch name{case "forecast_patient_volume":validated["metric"]="patient_arrivals";return s.postJSON(ctx,s.cfg.ForecastURL+"/forecast",validated);case "forecast_bed_occupancy":validated["metric"]="bed_occupancy";return s.postJSON(ctx,s.cfg.ForecastURL+"/forecast",validated);case "forecast_disease_incidence":validated["metric"]="disease_incidence";return s.postJSON(ctx,s.cfg.ForecastURL+"/forecast",validated);case "get_radiology_result":return s.getJSON(ctx,s.cfg.RadiologyURL+"/results/"+url.PathEscape(validated["result_id"].(string)));case "get_service_status":return json.Marshal(map[string]any{"gateway":"ready","processing":"local","services":s.serviceStatus(ctx)});default:return nil,fmt.Errorf("unknown tool: %s",name)} }
func (s *server) postJSON(ctx context.Context,endpoint string,value any)(json.RawMessage,error){ body,err:=json.Marshal(value);if err!=nil{return nil,err};req,err:=http.NewRequestWithContext(ctx,http.MethodPost,endpoint,bytes.NewReader(body));if err!=nil{return nil,err};req.Header.Set("Content-Type","application/json");resp,err:=s.client.Do(req);if err!=nil{return nil,err};defer resp.Body.Close();payload,err:=io.ReadAll(io.LimitReader(resp.Body,maxToolResponse));if err!=nil{return nil,err};if resp.StatusCode<200||resp.StatusCode>=300{return nil,fmt.Errorf("tool status %d: %s",resp.StatusCode,strings.TrimSpace(string(payload)))};if !json.Valid(payload){return nil,errors.New("tool returned invalid JSON")};return payload,nil }
func (s *server) getJSON(ctx context.Context,endpoint string)(json.RawMessage,error){ req,err:=http.NewRequestWithContext(ctx,http.MethodGet,endpoint,nil);if err!=nil{return nil,err};resp,err:=s.client.Do(req);if err!=nil{return nil,err};defer resp.Body.Close();payload,err:=io.ReadAll(io.LimitReader(resp.Body,maxToolResponse));if err!=nil{return nil,err};if resp.StatusCode<200||resp.StatusCode>=300{return nil,fmt.Errorf("tool status %d: %s",resp.StatusCode,strings.TrimSpace(string(payload)))};if !json.Valid(payload){return nil,errors.New("tool returned invalid JSON")};return payload,nil }
func (s *server) forecastProxy(w http.ResponseWriter,r *http.Request){s.proxyHTTP(w,r,s.cfg.ForecastURL+"/forecast")};func (s *server) radiologyProxy(w http.ResponseWriter,r *http.Request){s.proxyHTTP(w,r,s.cfg.RadiologyURL+"/analyze")}
func (s *server) radiologyResultProxy(w http.ResponseWriter,r *http.Request){id:=strings.TrimSpace(r.PathValue("id"));if id==""||len(id)>160{writeJSON(w,http.StatusBadRequest,map[string]string{"error":"invalid result id"});return};s.proxyHTTP(w,r,s.cfg.RadiologyURL+"/results/"+url.PathEscape(id))}
func (s *server) proxyHTTP(w http.ResponseWriter,r *http.Request,endpoint string){started:=time.Now();requestID:=fmt.Sprintf("req-%d",time.Now().UnixNano());w.Header().Set("X-NDHIS-Request-ID",requestID);req,err:=http.NewRequestWithContext(r.Context(),r.Method,endpoint,r.Body);if err!=nil{writeJSON(w,http.StatusBadRequest,map[string]string{"error":err.Error()});s.audit(r,requestID,r.URL.Path,"",http.StatusBadRequest,started);return};if contentType:=r.Header.Get("Content-Type");contentType!=""{req.Header.Set("Content-Type",contentType)};resp,err:=s.client.Do(req);if err!=nil{writeJSON(w,http.StatusBadGateway,map[string]string{"error":err.Error()});s.audit(r,requestID,r.URL.Path,"",http.StatusBadGateway,started);return};defer resp.Body.Close();if contentType:=resp.Header.Get("Content-Type");contentType!=""{w.Header().Set("Content-Type",contentType)};w.WriteHeader(resp.StatusCode);_,_=io.Copy(w,io.LimitReader(resp.Body,s.cfg.MaxBodyBytes));s.audit(r,requestID,r.URL.Path,"",resp.StatusCode,started)}
